### ISSUE TITLE
Upload initial Docker image with OpenJDK 11

### ISSUE THREAD

**Issue by wlsc** [corretto/corretto-11-docker#1]
Upload initial Docker image with OpenJDK 11

**Comment by wlsc** [comment]
btw, will be available a **slim** version as well?

**Comment by davecurrie** [comment]
@wlsc we are looking at the best way to deliver slim Docker images.

**Comment by EricEdens** [comment]
Addressing in #3

**Comment by EricEdens** [comment]
Fixed in #3
