### ISSUE TITLE
Minimal docker distribution

### ISSUE THREAD

**Issue by aprisak** [corretto/corretto-11-docker#13]
When using this for microservices it would be helpful to have a minimal distribution. The size of version 11.0.3 is 492MB. Amazon Linux is 162MB of this. It seems that other supported linux distributions have a smaller minimal package like Ubuntu which I believe goes somewhere between 30 and 40MB. Alpine would be nice but I do not see it as one of the listed supported distribution for the JDK.

In addition, I think it would make sense to remove all the development tools from the image like javadoc, jdep,...

Additionally, it would make sense to remove modules that are only used by clients like java.desktop as I do not see this as a use case for a docker container.

**Comment by yrsurya** [comment]
is there any update on this issue, we are also facing same. base image for amazonlinux is 160MB as mentioned but if we install corretto11 it is consuming more. is there any chance to get it down as our app itself 80 MB which we are trying to run.

**Comment by cliveverghese** [comment]
Thank you @yrsurya for your feedback. We have the docker image size reduction on our roadmap and we will update the issue when we have news

**Comment by gschnaubelt** [comment]
A [distroless](https://github.com/GoogleContainerTools/distroless) option would be ideal

**Comment by byrash** [comment]
So, is this also not going to be published I believe ? based on https://github.com/docker-library/official-images/pull/6886#issuecomment-561400888 ?

**Comment by benty-amzn** [comment]
For now, the suggested minimal distribution for Corretto 11 is the [alpine distribution from `corretto-docker`](https://github.com/corretto/corretto-docker/tree/main/11/jdk/alpine). This repository is deprecated in favor of that one. Closing this issue, please feel free to create a new one on the `corretto-docker` repository if you have further questions or concerns.
