### ISSUE TITLE
CVEs in the Amazon Linux 2 base Docker image

### ISSUE THREAD

**Issue by wkruse** [corretto/corretto-11-docker#18]
There are a couple of CVEs in the Amazon Linux 2, that is used as base Docker image for Corretto 11:

CVE SEVERITY | PACKAGE NAME | PACKAGE VERSION
--------------- | ---------------- | --------------------
Medium ALAS2-2019-1340 | curl | 7.61.1-11.amzn2.0.2
Medium ALAS2-2019-1340 | libcurl | 7.61.1-11.amzn2.0.2
Medium ALAS2-2019-1362 | openssl-libs | 1:1.0.2k-16.amzn2.1.1
Medium ALAS2-2019-1368 | python | 2.7.16-3.amzn2.0.1
Medium ALAS2-2019-1368 | python-libs | 2.7.16-3.amzn2.0.1
Medium ALAS2-2019-1370 | file-libs | 5.11-33.amzn2.0.2
Medium ALAS2-2019-1373 | libidn2 | 2.0.4-1.amzn2.0.2
Medium ALAS2-2020-1379 | nss-softokn | 3.44.0-5.amzn2.0.2
Medium ALAS2-2020-1379 | nss-softokn-freebl | 3.44.0-5.amzn2.0.2
Low ALAS2-2019-1337 | elfutils-libelf | 0.170-4.amzn2

Package updates are available for Amazon Linux 2 that fix them.

Does the quote below from the FAQs also applies to the Amazon Linux 2 base Docker image or is it Amazon Corretto only?

> Updates are planned to be released quarterly. Amazon also plans to apply urgent fixes (including security) outside of the regular quarterly cycle when they are available and ready to use.

https://aws.amazon.com/de/corretto/faqs/#support

**Comment by davecurrie** [comment]
@wkruse Thanks for the feedback. The Corretto Docker images in Docker Hub and ECR are built on the latest available AL2 images. They are updated automatically when a new AL2 image is available. This is a separate process from the quarterly release cycle, which only refers to Corretto JDK updates.

I'll get in touch with the AL2 team to see what the status is on those CVEs and get back on this issue.

**Comment by iliana** [comment]
Hi @wkruse, I currently publish the `amazonlinux` base image.

Issues affecting the base image can be made in our repository, https://github.com/amazonlinux/container-images.

This comment is still applicable: https://github.com/amazonlinux/container-images/issues/30#issuecomment-539620789

The latest update to the amazonlinux:2 base image was provided to the Docker Library project yesterday, which coincided with our recent AMI release. It still has the outstanding nss-softokn medium advisory (same as the AMI; this is an artifact of when the image was built being independent of when packages are published).

We are working on automating container image builds, but until that’s complete you may opt to add a `RUN yum update -y && yum clean all` to your Dockerfile. We know that’s not ideal, but we’re working on it.

If you have any further questions about the base image feel free to reach out on the amazonlinux/container-images issues.
