### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by chtompki** [corretto/corretto-11-docker#2]

**Comment by chtompki** [comment]
Pardon the period there in the title. All of my headings in grad school required periods.

**Comment by jhamberg** [comment]
Why exactly would this be necessary? I found it highly useful to be able to track the changes made here.

**Comment by chtompki** [comment]
I think it looks unpolished. So for the sake of image I would think we would want to make it private at least until we have a ‘README.md’ describing what’s going on here.

**Comment by alvdavi** [comment]
Thanks for reaching out, you both raise valid points.

We have added an explanatory README.md.
